// techQuestions.js

const techQuestions = [
  "What is the difference between AI and machine learning?",
  "How does blockchain technology work?",
  "What are the main features of 5G networks?",
  "How do quantum computers differ from classical computers?",
  "What is cloud computing?",
  "Explain the concept of edge computing.",
  "What is the Internet of Things (IoT)?",
  "How does a VPN work?",
  "What are microservices?",
  "What is serverless architecture?",
  "What are the advantages of using containers like Docker?",
  "How do Kubernetes and Docker differ?",
  "What is the purpose of APIs in software development?",
  "What is DevOps?",
  "How do continuous integration and continuous deployment work?",
  "What are the differences between SQL and NoSQL databases?",
  "What is a distributed ledger?",
  "How does AI impact cybersecurity?",
  "What is a zero-trust security model?",
  "What are some common programming paradigms?",
  "What is object-oriented programming?",
  "What is functional programming?",
  "What is event-driven programming?",
  "How do machine learning models get trained?",
  "What is natural language processing?",
  "What is computer vision?",
  "What is deep learning?",
  "What are neural networks?",
  "What is the difference between supervised and unsupervised learning?",
  "What is reinforcement learning?",
  "What is augmented reality?",
  "What is virtual reality?",
  "What is mixed reality?",
  "What are the key components of a computer?",
  "What is an operating system?",
  "What is the difference between Linux, Windows, and macOS?",
  "What are programming languages?",
  "What is the difference between compiled and interpreted languages?",
  "What is cybersecurity?",
  "What is encryption?",
  "What is a firewall?",
  "What are malware and ransomware?",
  "What is a phishing attack?",
  "What is a botnet?",
  "What is cloud storage?",
  "What are the differences between SaaS, PaaS, and IaaS?",
  "What is a data warehouse?",
  "What is big data?",
  "What is data mining?",
  "What is a data lake?",
  "What is edge AI?",
  "What is a digital twin?",
  "What is 3D printing?",
  "What is wearable technology?",
  "What is smart home technology?",
  "What is autonomous driving?",
  "What is a drone?",
  "What is robotics?",
  "What are exascale computers?",
  "What is a GPU used for?",
  "What is a CPU used for?",
  "What is RAM?",
  "What is ROM?",
  "What is cache memory?",
  "What is network latency?",
  "What is a CDN (Content Delivery Network)?",
  "What is HTTP and HTTPS?",
  "What is the difference between TCP and UDP?",
  "What is a DNS server?",
  "What is an IP address?",
  "What is IPv4 vs IPv6?",
  "What is a MAC address?",
  "What is a subnet?",
  "What is NAT (Network Address Translation)?",
  "What is cloud-native computing?",
  "What are webhooks?",
  "What is a progressive web app (PWA)?",
  "What is responsive web design?",
  "What is SEO in technology?",
  "What is a chatbot?",
  "What is a virtual assistant?",
  "What is speech recognition?",
  "What is image recognition?",
  "What are recommendation algorithms?",
  "What is a recommender system?",
  "What is the difference between AR and VR?",
  "What is telemedicine?",
  "What is fintech?",
  "What is edtech?",
  "What are smart contracts?",
  "What is cryptocurrency?",
  "What is a stablecoin?",
  "What is tokenization?",
  "What is decentralized finance (DeFi)?",
  "What is peer-to-peer networking?",
  "What is server virtualization?",
  "What is multi-cloud strategy?",
  "What is AI ethics?",
  "What is bias in AI?",
  "What is quantum encryption?",
  "What is edge security?",
  "What are microchips made of?",
  "What is Moore's Law?",
  "What is the difference between analog and digital signals?",
  "What is a touchscreen?",
  "What is a smart display?",
  "What is augmented analytics?",
  "What is low-code/no-code development?",
  "What are APIs used for in web development?",
  "What is web3?"
];

export default techQuestions;
